language: node_js

node_js:
  - "12.18.2"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE witter;" -U postgres
  - npm run migrations
