language: node_js

node_js:
  - "12.18.2"

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE witter;" -U postgres
<<<<<<< HEAD
  - npm run migrations-test
=======
  - npm run migrations
>>>>>>> 0e66055d22331e4ab4c578089691bb27e0babe44
